version: '3.1'
services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=flyinside
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
  apm-server:
    image: docker.elastic.co/apm/apm-server:6.3.2